version: '2'

services:
  kittenserver:
    build: ./server/.
    image: kittenserver:gomicro
    command: sh -c 'sleep 5 && /kittenserver --registry_address=consul:8500'
    links:
      - consul

  consul:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
