version: '2'

services:
  kittenserver:
    build: ./server/.
    image: kittenserver:kite
    command: sh -c '/kittenserver'
    ports:
      - 8091:8091
      - 6060:6060
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
  kontrol:
    build: ./kontrol/.
    image: kittenserver:kontrol
    command: /kontrol/kontrol
  etcd:
    image: elcolio/etcd

